In [ ]:
x = 5

In [ ]:
type(x)

int

In [ ]:
y = 5.0
type(y)

float

In [ ]:
x + y

10.0

In [ ]:
z = """this is a multine quote
and i can type in more than one line using 
these quotes"""

In [ ]:
print(z)

this is a multine quote
and i can type in more than one line using 
these quotes


In [ ]:
print(type(z))

<class 'str'>


In [ ]:
#lists are used as arrays in python
a_list = [1, 2, 3, 4, 5, 6, 7, "string"]
a_list

[1, 2, 3, 4, 5, 6, 7, 'string']

In [ ]:
type(a_list)

list

In [ ]:
type(a_list[7])

str

In [ ]:
a_list[-1]

'string'

In [ ]:
a_list[::-1]

['string', 7, 6, 5, 4, 3, 2, 1]

In [ ]:
#tuples are lists that cannot be modified
a_tuple = {1, 2, 3, 4, 5}
a_tuple

{1, 2, 3, 4, 5}

In [ ]:
type(a_tuple)

set

In [ ]:
#a dictionary consists of key-value pairs
dictionary = {"Name":"Samarth", "Age":13}

In [ ]:
dictionary

{'Name': 'Samarth', 'Age': 13}

In [ ]:
type(dictionary)

dict

In [ ]:
dictionary["Name"]

'Samarth'

In [ ]:
dictionary .get("Age")

13

In [ ]:
add = 2 + 2

In [ ]:
add

4

In [ ]:
add_strings = 'Samarth' + ' in USA'
add_strings

'Samarth in USA'

In [ ]:
add_list = [1, 2, 3, 4] + [1, 2, 3]

In [ ]:
add_list

[1, 2, 3, 4, 1, 2, 3]

In [ ]:
multiply_list = [1, 2, 3, 4] * 5
                              

In [ ]:
multiply_list

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
def our_function(x, y, z):
  sum = x + y + z
  return sum

In [ ]:
our_function(-10, 3, 4)

-3

In [ ]:
import numpy as np

In [ ]:
np.array([1, 2, 4])

array([1, 2, 4])

In [ ]:
the_list = list(range(3, 10))

In [ ]:
print(the_list)

[3, 4, 5, 6, 7, 8, 9]


In [ ]:
for i in the_list:
  i += 1
  print(i)


4
5
6
7
8
9
10


In [ ]:
x = 0
while x < 5:
  x += 1
  print(x)

1
2
3
4
5


In [ ]:
import numpy as np

In [ ]:
a = np.array([2, 3, 4])

In [ ]:
a

array([2, 3, 4])

In [ ]:
c = np.array([2, 3, 4, 5, 6, 2]).reshape(2, 3)

In [ ]:
c

array([[2, 3, 4],
       [5, 6, 2]])

In [ ]:
e = np.array([1, 2, 3, 4, 5, 6])
print(e.sum())

21


In [ ]:
print(e.min())

1


In [ ]:
print(e.max())

6


In [ ]:
print(e.mean())

3.5


In [ ]:
#special case arrays
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#linspace is used to create an evenly spaced sequence within a specified range
np.linspace(0, 6, 10)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [ ]:
#the following code gives us three random numbers between o and 1
np.random.rand(3)

array([0.14060069, 0.20908765, 0.53010603])

In [ ]:
#the following code gives us a random integer from the specified range
np.random.randint(1,100)

37

In [ ]:
print('np is a useful library')

np is a useful library


In [ ]:
#creates the required range
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [2]:
import pandas as pd

In [3]:
series_test = list(range(1, 100))

In [4]:
series_test

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [5]:
pd.Series(series_test)

0      1
1      2
2      3
3      4
4      5
      ..
94    95
95    96
96    97
97    98
98    99
Length: 99, dtype: int64

In [14]:
df = pd.read_csv("simple_csv.csv")
df.head(10)

Column1   Column2   Column3
0  0.280925  0.910368  0.692982
1  0.719882  0.210024  0.761276
2  0.235752  0.059796  0.154667
3  0.603366  0.485614  0.013345
4  0.039985  0.236359  0.811832
5  0.015478  0.543641  0.112719
6  0.192540  0.409874  0.875082
7  0.380921  0.045468  0.515859
8  0.592471  0.786421  0.047249
9  0.072112  0.695694  0.409573

In [8]:
column1_mean = round(df.Column1.mean(), 2)
column2_mean = round(df.Column2.mean(), 3)
column3_mean = round(df.Column3.mean(), 2)
print(f"{column1_mean} is the mean of the first column of the dataset")
print(f"{column2_mean} is the mean of the second column of the dataset")
print(f"{column3_mean} is the mean of the third column of the dataset")

0.49 is the mean of the first column of the dataset
0.404 is the mean of the second column of the dataset
0.44 is the mean of the third column of the dataset


In [10]:
print(df)

     Column1   Column2   Column3
0   0.280925  0.910368  0.692982
1   0.719882  0.210024  0.761276
2   0.235752  0.059796  0.154667
3   0.603366  0.485614  0.013345
4   0.039985  0.236359  0.811832
5   0.015478  0.543641  0.112719
6   0.192540  0.409874  0.875082
7   0.380921  0.045468  0.515859
8   0.592471  0.786421  0.047249
9   0.072112  0.695694  0.409573
10  0.898072  0.070956  0.209020
11  0.722038  0.211985  0.324164
12  0.513517  0.091548  0.664279
13  0.436729  0.040322  0.548167
14  0.864039  0.963556  0.106398
15  0.724761  0.410422  0.587589
16  0.198926  0.245207  0.767356
17  0.748500  0.019264  0.046678
18  0.920639  0.212611  0.520463
19  0.452024  0.123660  0.847451
20  0.542977  0.265852  0.410926
21  0.355266  0.860616  0.589431
22  0.142688  0.406456  0.204095
23  0.850436  0.129426  0.719027
24  0.443476  0.388967  0.596924
25  0.467100  0.416908  0.098037
26  0.338536  0.935814  0.736899
27  0.942101  0.772005  0.441574
28  0.570130  0.780085  0.085592


In [15]:
df.Column1

0     0.280925
1     0.719882
2     0.235752
3     0.603366
4     0.039985
5     0.015478
6     0.192540
7     0.380921
8     0.592471
9     0.072112
10    0.898072
11    0.722038
12    0.513517
13    0.436729
14    0.864039
15    0.724761
16    0.198926
17    0.748500
18    0.920639
19    0.452024
20    0.542977
21    0.355266
22    0.142688
23    0.850436
24    0.443476
25    0.467100
26    0.338536
27    0.942101
28    0.570130
Name: Column1, dtype: float64

In [17]:
df["Column3"]

0     0.692982
1     0.761276
2     0.154667
3     0.013345
4     0.811832
5     0.112719
6     0.875082
7     0.515859
8     0.047249
9     0.409573
10    0.209020
11    0.324164
12    0.664279
13    0.548167
14    0.106398
15    0.587589
16    0.767356
17    0.046678
18    0.520463
19    0.847451
20    0.410926
21    0.589431
22    0.204095
23    0.719027
24    0.596924
25    0.098037
26    0.736899
27    0.441574
28    0.085592
Name: Column3, dtype: float64

In [27]:
df["a"] = 1

In [28]:
df["b"] = list(range(29))

In [29]:
df["a + b"] = df["a"] + df["b"]

In [30]:
df.head(5)

Column1   Column2   Column3  New_Column  New_Colum_2  a  b  a + b
0  0.280925  0.910368  0.692982           1            0  1  0      1
1  0.719882  0.210024  0.761276           1            1  1  1      2
2  0.235752  0.059796  0.154667           1            2  1  2      3
3  0.603366  0.485614  0.013345           1            3  1  3      4
4  0.039985  0.236359  0.811832           1            4  1  4      5

In [33]:
df.drop("New_Column", axis = 1)
df.drop("New_Colum_2", axis = 1)

Column1   Column2   Column3  New_Column  a   b  a + b
0   0.280925  0.910368  0.692982           1  1   0      1
1   0.719882  0.210024  0.761276           1  1   1      2
2   0.235752  0.059796  0.154667           1  1   2      3
3   0.603366  0.485614  0.013345           1  1   3      4
4   0.039985  0.236359  0.811832           1  1   4      5
5   0.015478  0.543641  0.112719           1  1   5      6
6   0.192540  0.409874  0.875082           1  1   6      7
7   0.380921  0.045468  0.515859           1  1   7      8
8   0.592471  0.786421  0.047249           1  1   8      9
9   0.072112  0.695694  0.409573           1  1   9     10
10  0.898072  0.070956  0.209020           1  1  10     11
11  0.722038  0.211985  0.324164           1  1  11     12
12  0.513517  0.091548  0.664279           1  1  12     13
13  0.436729  0.040322  0.548167           1  1  13     14
14  0.864039  0.963556  0.106398           1  1  14     15
15  0.724761  0.410422  0.587589           1  1  15     16
16  0.198926  0.245207  0.767356           1  1  16     17
17  0.748500  0.019264  0.046678           1  1  17     18
18  0.920639  0.212611  0.520463           1  1  18     19
19  0.452024  0.123660  0.847451           1  1  19     20
20  0.542977  0.265852  0.410926           1  1  20     21
21  0.355266  0.860616  0.589431           1  1  21     22
22  0.142688  0.406456  0.204095           1  1  22     23
23  0.850436  0.129426  0.719027           1  1  23     24
24  0.443476  0.388967  0.596924           1  1  24     25
25  0.467100  0.416908  0.098037           1  1  25     26
26  0.338536  0.935814  0.736899           1  1  26     27
27  0.942101  0.772005  0.441574           1  1  27     28
28  0.570130  0.780085  0.085592           1  1  28     29

In [36]:
df.loc[0:2]

Column1   Column2   Column3  New_Column  New_Colum_2  a  b  a + b
0  0.280925  0.910368  0.692982           1            0  1  0      1
1  0.719882  0.210024  0.761276           1            1  1  1      2
2  0.235752  0.059796  0.154667           1            2  1  2      3

In [37]:
df.drop(columns = "New_Column", inplace = True)

In [38]:
df.head(5)

Column1   Column2   Column3  New_Colum_2  a  b  a + b
0  0.280925  0.910368  0.692982            0  1  0      1
1  0.719882  0.210024  0.761276            1  1  1      2
2  0.235752  0.059796  0.154667            2  1  2      3
3  0.603366  0.485614  0.013345            3  1  3      4
4  0.039985  0.236359  0.811832            4  1  4      5

In [39]:
df.drop(columns = "New_Colum_2", inplace = True)

In [40]:
df.head(5)

Column1   Column2   Column3  a  b  a + b
0  0.280925  0.910368  0.692982  1  0      1
1  0.719882  0.210024  0.761276  1  1      2
2  0.235752  0.059796  0.154667  1  2      3
3  0.603366  0.485614  0.013345  1  3      4
4  0.039985  0.236359  0.811832  1  4      5

In [47]:
df.loc[0:5, ["Column2",	"Column3",	"a",	"b",	"a + b"]]

Column2   Column3  a  b  a + b
0  0.910368  0.692982  1  0      1
1  0.210024  0.761276  1  1      2
2  0.059796  0.154667  1  2      3
3  0.485614  0.013345  1  3      4
4  0.236359  0.811832  1  4      5
5  0.543641  0.112719  1  5      6

In [53]:
df.iloc[0:6, [1, 2, 3, 4, 5]]

Column2   Column3  a  b  a + b
0  0.910368  0.692982  1  0      1
1  0.210024  0.761276  1  1      2
2  0.059796  0.154667  1  2      3
3  0.485614  0.013345  1  3      4
4  0.236359  0.811832  1  4      5
5  0.543641  0.112719  1  5      6